language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio

env:
- BOARD=esp01
- BOARD=nodemcuv2

script:
- for e in examples/*; do
    platformio ci --board=$BOARD --lib=. $e/*;
  done