language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - BOARD=esp01 PLATFORMIO_CI_SRC=examples/SimpleLoggingESP8266
    - BOARD=nodemcuv2 PLATFORMIO_CI_SRC=examples/SimpleLoggingESP8266
    - BOARD=uno PLATFORMIO_CI_SRC=examples/SimpleLogging
    - BOARD=megaatmega1280 PLATFORMIO_CI_SRC=examples/SimpleLogging

install:
    - pip install -U platformio

script:
    - platformio ci -v --lib="." --board=$BOARD